// <auto-generated />
using System;
using InterviewService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewService.Infrastructure.Migrations
{
    [DbContext(typeof(InterviewServiceDbContext))]
    [Migration("20260509150940_RenameInterviewSetupIdToHashGuid")]
    partial class RenameInterviewSetupIdToHashGuid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewService.Infrastructure.Models.PostgresInterviewDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("SetupHashGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("setup_hash_guid");

                    b.HasKey("Id")
                        .HasName("pk_interviews");

                    b.HasIndex("SetupHashGuid")
                        .HasDatabaseName("ix_interviews_setup_hash_guid");

                    b.ToTable("interviews", (string)null);
                });

            modelBuilder.Entity("InterviewService.Infrastructure.Models.PostgresInterviewSetupDto", b =>
                {
                    b.Property<Guid>("HashGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("hash_guid");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("group_name");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.HasKey("HashGuid")
                        .HasName("pk_interview_setups");

                    b.HasIndex("GroupName")
                        .HasDatabaseName("ix_interview_setups_group_name");

                    b.ToTable("interview_setups", (string)null);
                });

            modelBuilder.Entity("InterviewService.Infrastructure.Models.PostgresInterviewDto", b =>
                {
                    b.HasOne("InterviewService.Infrastructure.Models.PostgresInterviewSetupDto", "Setup")
                        .WithMany("Interviews")
                        .HasForeignKey("SetupHashGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interviews_interview_setups_setup_hash_guid");

                    b.Navigation("Setup");
                });

            modelBuilder.Entity("InterviewService.Infrastructure.Models.PostgresInterviewSetupDto", b =>
                {
                    b.Navigation("Interviews");
                });
#pragma warning restore 612, 618
        }
    }
}
